### ISSUE TITLE
No longer works with type-graphql 1.0.0-rc.2

### ISSUE THREAD

**Issue by russell-dot-js** [Urigo/graphql-modules#1214]
Just a heads up - this might not be an issue, but check out https://github.com/MichalLytek/type-graphql/issues/662

The TypeGraphQL integration no longer works as documented. I will update here if the type-graphql team says it's an issue on graphql-modules' end.

**Comment by agustif** [comment]
Hey I was gonna try and use TypeGraphQL+GraphQL-Modules.

Subscribe to this to see how it goes.

**Comment by smolinari** [comment]
I'm interested in this issue too.

Scott

**Comment by MichalLytek** [comment]
It's working with `1.0.0`:
https://github.com/MichalLytek/type-graphql/tree/master/examples/graphql-modules

**Comment by agustif** [comment]
> It's working with `1.0.0`:
> https://github.com/MichalLytek/type-graphql/tree/master/examples/graphql-modules

Awesome, will try right away!
Thanks for letting us know.

**Comment by MichalLytek** [comment]
btw, is there a way to provide the extra schema in an async way? The docs recomends `buildSchemaSync` which is a workaround without proper async checks enabled.

**Comment by agustif** [comment]
> It's working with `1.0.0`:
> https://github.com/MichalLytek/type-graphql/tree/master/examples/graphql-modules

I get the foolowing error when running with ts-node: TypeGraphQLMetadataStorage does not exist on type Global & typeof globalThis

```
type-graphql on  master [?] is 📦 v0.0.0-unreleased via ⬢ v12.14.1 took 3m 51s 
➜ cd examples/graphql-modules 

type-graphql/examples/graphql-modules on  master [?] 
➜ node index.ts
/home/agus/type-graphql/examples/graphql-modules/index.ts:1
import "reflect-metadata";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

type-graphql/examples/graphql-modules on  master [?] 
➜ ts-node index.ts 

/home/agus/.config/yarn/global/node_modules/ts-node/src/index.ts:434
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
../../src/metadata/getMetadataStorage.ts:5:12 - error TS2339: Property 'TypeGraphQLMetadataStorage' does not exist on type 'Global & typeof globalThis'.' does not exist on type 'Global & typeof globalThis'.

5     global.TypeGraphQLMetadataStorage || (global.TypeGraphQLMetadataStorage = new MetadataStorage())e())                                                                                                                                           balThis'.
             ~~~~~~~~~~~~~~~~~~~~~~~~~~                                                           ' does not exist on type 'Global & typeof glo
../../src/metadata/getMetadataStorage.ts:5:50 - error TS2339: Property 'TypeGraphQLMetadataStorage' does not exist on type 'Global & typeof globalThis'.
                                                                                                  e())
5     global.TypeGraphQLMetadataStorage || (global.TypeGraphQLMetadataStorage = new MetadataStorage())
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/agus/.config/yarn/global/node_modules/ts-node/src/index.ts:434:12)                                                 es/cjs/loader.js:991:10)
    at reportTSError (/home/agus/.config/yarn/global/node_modules/ts-node/src/index.ts:438:19)    
    at getOutput (/home/agus/.config/yarn/global/node_modules/ts-node/src/index.ts:578:36)            at Module._extensions..js (internal/modul
    at Object.compile (/home/agus/.config/yarn/global/node_modules/ts-node/src/index.ts:775:32)   
    at Module.m._compile (/home/agus/.config/yarn/global/node_modules/ts-node/src/index.ts:858:43)ts-node/src/index.ts:861:12)
```

**Comment by MichalLytek** [comment]
@agustif It's a known ts-node issue - just run with `ts-node --transpile-only index.ts`

**Comment by agustif** [comment]
> @agustif It's a known ts-node issue - just run with `ts-node --transpile-only index.ts`

Thank you very much, indeed that was it (wasn't aware of it)

It runs perfectly now, thanks for updating the example and helping me out.

Will start my backend now!

**Comment by harm-less** [comment]
> It's working with `1.0.0`:
> https://github.com/MichalLytek/type-graphql/tree/master/examples/graphql-modules

@MichalLytek I don't think your example is using version `1.0.0` just yet.

**Comment by smolinari** [comment]
@harm-less - Do you mean 1.0 of GraphQL-Modules or Type-GraphQL. Because, 1.0 was working with the pre 1.0 of GQL-Modules for sure. Type-GraphQL definitely doesn't work with 1.0 of GraphQL-Modules, at least not without major rework....

Scott

**Comment by harm-less** [comment]
@smolinari Yes, I meant GraphQL-Modules. Without the `extraSchemas` it's going to be hard.

**Comment by MichalLytek** [comment]
@harm-less The issue title is "type-graphql 1.0.0-rc.2" so I pasted the link to show how to use GraphQL Modules 0.x with `type-graphql@1.0.0`.

**Comment by harm-less** [comment]
@MichalLytek I see, it makes sense now, I think I mixed a few things up and I assumed this was also about GraphQL-Modules `1.0.0`. Sorry for the confusion. I'm using Type-GraphQL `1.0.0` as well in combination with GraphQL-Modules `0.7`, so I can confirm it works as well.

**Comment by smolinari** [comment]
@harm-less - Because of what happened to GraphQL-Modules in v1, I've now moved to NestJS. I'm not using TypeGraphQL with Nest because Nest's GraphQL module seems to be covering my needs (currently). 😃 We'll see what the future brings.....  

Scott

**Comment by kamilkisiela** [comment]
Closing in favor of #1466
